server:
  port: 8103
spring:
  application:
    name: eureka-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ellaend:123456@localhost:8004/eureka/