server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  routes: #给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**


#默认情况，与 Eureka结合，实现路由自动配置，相当如下配置
#zuul:
#  routes: #给服务配置路由
#    user-service:
#      path: /user-service/**
#    feign-service:
#      path: /feign-service/**

#路由路径添加前缀
#zuul:
#  prefix:

#开启查看路由的端点
management:
  endpoints:
    web:
      exposure:
        include: 'routes'
