server:
  port: 8002
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: replica1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://replica2:8003/eureka #注册到另一个 eureka 注册中心